### ISSUE TITLE
Overall comment 

### ISSUE THREAD

**Issue by minkooii** [vntan/HeartFailureAnalysis#2]
I find your project very practical and useful for treating people health especially to avoid heart diseases.
- In data exploring step:
     + The dataset your team got is quite diverse in terms of information.
     + Your group understand your dataset quite well. 
     + You use many types of data visualization and the way you chose suitable chart for presenting your data is very good so readers can also understand your data well.
- In data analysis step:
     + Your team make very good questions which seem to be useful to solve problems bearing with heart diseases.
     + Using appropriate machine learning to solve problem.
     + It would be perfect if your team present your answer with some charts
20127214-Nguyễn Trương Minh Khôi

**Comment by TrungTechh** [comment]
I have the same thought with Minh Khôi, your project is so meaningful. But i got some opinions:

- I don't know why some attributes like `RestingBP`  <= 20 , `Cholesterol` <= 60.3, `Oldpeak` <= 0.04 be considered as not suitable? You should explain at that point.
- After answer a question, you should have conclusion or explanation about your answer. And it need be simple for reader who have no domain knowledge

My infor: 20127655 - Trần Quốc Trung

**Comment by lephu13502** [comment]
Quá xuất sắc và rất thiết thực.
MSSV: 20127275 - Lê Nguyễn Nhật Phú

**Comment by vntan** [comment]
Thanks for your feedbacks.
